# List of columns used for training the model
train_columns = [
    'view_count', 'price', 'inv_value_sum', 'game_count_sum', 'level_sum',
    'price_per_view', 'total_steam_games', 'total_playtime', 'std_playtime',
    'published_date_year', 'published_date_month', 'published_date_day',
    'published_date_hour', 'published_date_minute', 'published_date_second',
    'published_date_weekday', 'published_date_is_weekend',
    'update_stat_date_year', 'update_stat_date_month', 'update_stat_date_day',
    'update_stat_date_hour', 'update_stat_date_minute', 'update_stat_date_second',
    'update_stat_date_weekday', 'update_stat_date_is_weekend',
    'refreshed_date_year', 'refreshed_date_month', 'refreshed_date_day',
    'refreshed_date_hour', 'refreshed_date_minute', 'refreshed_date_second',
    'refreshed_date_weekday', 'refreshed_date_is_weekend',
    'steam_register_date_year', 'steam_register_date_month', 'steam_register_date_day',
    'steam_register_date_hour', 'steam_register_date_minute', 'steam_register_date_second',
    'steam_register_date_weekday', 'steam_register_date_is_weekend',
    'steam_last_activity_year', 'steam_last_activity_month', 'steam_last_activity_day',
    'steam_last_activity_hour', 'steam_last_activity_minute', 'steam_last_activity_second',
    'steam_last_activity_weekday', 'steam_last_activity_is_weekend',
    'item_origin_account', 'item_origin_market', 'extended_guarantee_0',
    'extended_guarantee_1', 'nsb_0', 'nsb_1', 'email_type_mail',
    'email_type_proton', 'item_domain_gmail.com', 'item_domain_mail.ru',
    'item_domain_yandex.ru', 'resale_item_origin_account',
    'resale_item_origin_market', 'steam_country_BY', 'steam_country_KZ',
    'steam_country_RU', 'steam_community_ban_0', 'steam_community_ban_1',
    'steam_is_limited_0', 'steam_is_limited_1', 'steam_cs2_wingman_rank_id_0',
    'steam_cs2_wingman_rank_id_1', 'steam_cs2_rank_id_0', 'steam_cs2_rank_id_1',
    'steam_cs2_ban_type_0', 'steam_cs2_ban_type_1', 'steam_currency_RUB',
    'steam_currency_USD'
]
